name: CI setup for Go #Name of the workflow
on: #On event keyword
  push:
    branches: [main] #Identifying branch
    
jobs: #Job to execute on event
  my-job:
    name: My Job
    runs-on: ubuntu-16.04 #Specify OS in virtual machine
    steps:
    - name: Print a greeting
      run: |
        ls
        echo Hello there! #run terminal command
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3
      with:
        # The Go version to download (if necessary) and use. Supports semver spec and ranges.
        go-version: 1.16.5 # optional
    - name: Show Go version #Verify that go is installed
      run: go version #Show Go version
      
    - name: Checkout our codes #Bring repo code to virtual environment
      uses: actions/checkout@v2
      
    - name: Check file system #Check virtual environment has my files
      run: |
        ls
        cat calc.go #Prints the content of calc.go
    - name: Checkout private repo remotely
      uses: actions/checkout@v2
      with:
        repository: lowkh2/GoSchoolRemoteExample #The hidden repo I am trying to access
        path: virtualRepoFolder #Folder to save to in my virtual env
        token: ${{ secrets.GO_SECRET_DEMO }}
    - name: Show hidden files
      run: |
        cd virtualRepoFolder #To access folder of interest in my virtual env
        ls
        cat myText.txt #Show content of the file of interest
        cd ..
